/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface GameState {
  'status' : string,
  'moves' : Array<string>,
  'lastHeartbeat1' : bigint,
  'lastHeartbeat2' : bigint,
  'difficulty' : string,
  'createdAt' : bigint,
  'player1' : Principal,
  'player2' : [] | [Principal],
  'disconnectWinner' : [] | [Principal],
  'jetonPot' : bigint,
  'sessionId' : string,
}
export interface LeaderboardEntry {
  'xp' : bigint,
  'title' : string,
  'username' : string,
  'jetonBalance' : bigint,
  'user' : Principal,
}
export interface UserProfile {
  'xp' : bigint,
  'title' : string,
  'username' : string,
  'jetonBalance' : bigint,
  'code' : string,
  'registeredAt' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkDisconnect' : ActorMethod<[string], [] | [Principal]>,
  'createGameSession' : ActorMethod<[string, bigint, string], undefined>,
  'deleteAccount' : ActorMethod<[], undefined>,
  'getActiveGameSessions' : ActorMethod<[], Array<GameState>>,
  'getAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGameMoves' : ActorMethod<[string], Array<string>>,
  'getGameSession' : ActorMethod<[string], [] | [GameState]>,
  'getLeaderboard' : ActorMethod<[], Array<LeaderboardEntry>>,
  'getSystemStatistics' : ActorMethod<
    [],
    { 'averageXP' : bigint, 'totalJetons' : bigint, 'totalUsers' : bigint }
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinGameSession' : ActorMethod<[string, bigint], undefined>,
  'registerUser' : ActorMethod<[string], string>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendJetonsToAllUsers' : ActorMethod<[bigint, string], undefined>,
  'sendJetonsToUser' : ActorMethod<[string, bigint, string], undefined>,
  'submitMove' : ActorMethod<[string, string], undefined>,
  'updateJetonBalance' : ActorMethod<[bigint], undefined>,
  'updatePlayerHeartbeat' : ActorMethod<[string], undefined>,
  'updateXP' : ActorMethod<[bigint], string>,
  'validateLoginCode' : ActorMethod<[string], [] | [Principal]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];