/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const GameState = IDL.Record({
  'status' : IDL.Text,
  'difficulty' : IDL.Text,
  'createdAt' : IDL.Int,
  'player1' : IDL.Principal,
  'player2' : IDL.Opt(IDL.Principal),
  'jetonPot' : IDL.Nat,
  'sessionId' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'xp' : IDL.Int,
  'title' : IDL.Text,
  'username' : IDL.Text,
  'jetonBalance' : IDL.Nat,
  'code' : IDL.Text,
  'registeredAt' : IDL.Int,
});
export const LeaderboardEntry = IDL.Record({
  'xp' : IDL.Int,
  'title' : IDL.Text,
  'username' : IDL.Text,
  'jetonBalance' : IDL.Nat,
  'user' : IDL.Principal,
});

export const idlService = IDL.Service({
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createGameSession' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
  'getActiveGameSessions' : IDL.Func([], [IDL.Vec(GameState)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGameSession' : IDL.Func([IDL.Text], [IDL.Opt(GameState)], ['query']),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
  'getSystemStatistics' : IDL.Func(
      [],
      [
        IDL.Record({
          'averageXP' : IDL.Int,
          'totalJetons' : IDL.Nat,
          'totalUsers' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinGameSession' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'registerUser' : IDL.Func([IDL.Text], [IDL.Text], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendJetonsToAllUsers' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'sendJetonsToUser' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
  'updateJetonBalance' : IDL.Func([IDL.Int], [], []),
  'updateXP' : IDL.Func([IDL.Int], [IDL.Text], []),
  'validateLoginCode' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Principal)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const GameState = IDL.Record({
    'status' : IDL.Text,
    'difficulty' : IDL.Text,
    'createdAt' : IDL.Int,
    'player1' : IDL.Principal,
    'player2' : IDL.Opt(IDL.Principal),
    'jetonPot' : IDL.Nat,
    'sessionId' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'xp' : IDL.Int,
    'title' : IDL.Text,
    'username' : IDL.Text,
    'jetonBalance' : IDL.Nat,
    'code' : IDL.Text,
    'registeredAt' : IDL.Int,
  });
  const LeaderboardEntry = IDL.Record({
    'xp' : IDL.Int,
    'title' : IDL.Text,
    'username' : IDL.Text,
    'jetonBalance' : IDL.Nat,
    'user' : IDL.Principal,
  });
  
  return IDL.Service({
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createGameSession' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
    'getActiveGameSessions' : IDL.Func([], [IDL.Vec(GameState)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGameSession' : IDL.Func([IDL.Text], [IDL.Opt(GameState)], ['query']),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
    'getSystemStatistics' : IDL.Func(
        [],
        [
          IDL.Record({
            'averageXP' : IDL.Int,
            'totalJetons' : IDL.Nat,
            'totalUsers' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinGameSession' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'registerUser' : IDL.Func([IDL.Text], [IDL.Text], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendJetonsToAllUsers' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'sendJetonsToUser' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
    'updateJetonBalance' : IDL.Func([IDL.Int], [], []),
    'updateXP' : IDL.Func([IDL.Int], [IDL.Text], []),
    'validateLoginCode' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Principal)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };